### ISSUE TITLE
cp -R fails

### ISSUE THREAD

**Issue by msiemens** [lionello/onedrive-cli#19]
Trying to copy a directory recursively fails with this error:

```
onedrive-cli cp -R Documents .
GET /drive/root:/-R:/children
That item seems to be missing. Someone may have deleted or moved the item, or you may not have permission to view it.
```

Seems like `-R` is passed as a folder here:

https://github.com/lionello/onedrive-cli/blob/5deafe333d90c62905a6dc760ed68411cbb4186b/bin/onedrive#L458-L471

Here, `args` has the following value before being iterated: `[ '-R', 'Documents', '.' ]`

If I remove the first argument before doing the recursive copy, everything works fine.

**Comment by lionello** [comment]
Ah! This is a regression from 00a537ddc7a388c13af72a0cfd2d6903c8a59187. Thanks for catching it!

**Comment by msiemens** [comment]
Thanks for fixing this so quickly 🙂
