### ISSUE TITLE
sintax incorrect

### ISSUE THREAD

**Issue by BlueNickDev** [lionello/onedrive-cli#2]
install guide incorrect.

The correct sintax is with the "./" .
**./**onedrive COMMAND [arguments] and not onedrive COMMAND [arguments]

**Comment by lionello** [comment]
Hey, thanks for the report.

The Readme was showing how to add `onedrive` to your path. I fixed the readme to show easier usage. 16b1593a07ed341da5e127397827a327b042b209

Thanks!
